name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup
      run: npm ci

    - name: Testing
      run: npm run test_coverage
      continue-on-error: true

    - name: Coveralls 
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ github.token }}
    
